### PR TITLE
adding comment about pivot in the troubleshooting guide

### PR DESCRIPTION
**Pull request by Grummfy**

### CODE REVIEW

**Comment by quetzyg** [comment]
Sorry, I don't see the point in this.

**Comment by Grummfy** [comment]
the point is to help people see that there is a limitation, limitation that can be important for some of them.

**Comment by quetzyg** [comment]
It's a limitation everywhere you use Eloquent, it's not specific to this package.

**Comment by Grummfy** [comment]
Yes, But I think it's important to know it. Personally, I was surprise to see it and take the time to search in the issue about it.

**Pull request closed without merging**
